WNC\SoldierBundle\Entity\Soldier:
    properties:
        file:
            - Image: {groups: [Soldier]}
            - NotBlank: ~
            
            
Application\Sonata\UserBundle\Entity\User:
    properties:
      firstname:
        - NotBlank: ~
      lastname:
        - NotBlank: ~