WNC\SoldierBundle\Entity\Soldier:
    constraints:
        - Callback:
            methods:   [isServiceEndDateValid]


WNC\SoldierBundle\Entity\Participant:
    constraints:
        - Callback:
            methods:   [isActivityDatesValid]
            
            
Application\Sonata\UserBundle\Entity\User:
    properties:
      firstname:
        - NotBlank: { groups: [Soldier, Participant] }
      lastname:
        - NotBlank: { groups: [Participant]}
