<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{

  
    /**
     * @var integer $id
     */
    protected $id;
    
    /**
     * @var \WNC\SoldierBundle\Entity\Soldier
     */
    protected $soldier;
    
    /**
     *
     * @var \WNC\SoldierBundle\Entity\Participant
     */
    protected $participant;

    protected $openPassword;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    
        // override methods for username and tie them with email field
    
    
    public function __toString()
    {
        return sprintf('%s %s (%s)', $this->getFirstname(), $this->getLastname(), $this->getUsername());
    }
    
    /**
     * 
     * @return \WNC\SoldierBundle\Entity\Soldier
     */
    public function getSoldier()
    {
      return $this->soldier;
    }
    
    public function setSoldier(\WNC\SoldierBundle\Entity\Soldier $soldier)
    {
      $this->soldier = $soldier;
      $soldier->setUser($this);
    }
    
    /**
     * 
     * @return \WNC\SoldierBundle\Entity\Participant
     */
    public function getParticipant()
    {
      return $this->participant;
    }
    
    public function setParticipant(\WNC\SoldierBundle\Entity\Participant $participant)
    {
      $this->participant = $participant;
      $participant->setUser($this);
    }
    
    public function setPlainPassword($password) {
      
      $this->openPassword = $password;
      parent::setPlainPassword($password);
    }
    public function getOpenPassword() {
      return $this->openPassword;
    }

    public function setOpenPassword($openPassword) {
      $this->openPassword = $openPassword;
    }
    
        /**
     * Sets the email.
     *
     * @param string $email
     * @return User
     */
    public function setEmail($email)
    {
        $this->setUsername($email);

        return parent::setEmail($email);
    }

    /**
     * Set the canonical email.
     *
     * @param string $emailCanonical
     * @return User
     */
    public function setEmailCanonical($emailCanonical)
    {
        $this->setUsernameCanonical($emailCanonical);

        return parent::setEmailCanonical($emailCanonical);
    }
    
    public function getType()
    {
      
      return $this->getParticipant() ? 'participant' : 'soldier';
      
    }
    
}