<?php

namespace WNC\SoldierBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SoldierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoldierRepository extends EntityRepository
{
}
